codecov:
  branch: main

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: ddd-lite
      paths:
        - packages/shared/ddd-lite/**
    - component_id: infra-core
      paths:
        - packages/shared/infra-core/**
    - component_id: runtime-core
      paths:
        - packages/shared/runtime-core/**
